const estimates = {
  'hvac repair': { task: 'HVAC Repair', diyCost: '50-150', proCost: '150-600', diyTime: '1-3 hours', proTime: 'Same day', tips: ['Replace filters yourself to prevent issues ($10-30)', 'Get quotes from 3+ companies', 'Schedule in spring/fall for lower prices', 'Ask about maintenance plans for discounts'], recommendation: 'DIY for filter changes and thermostat issues. Call a pro for refrigerant, electrical, or mechanical problems.' },
  'hvac replacement': { task: 'HVAC System Replacement', diyCost: 'N/A — Pro required', proCost: '4,000-12,000', diyTime: 'N/A', proTime: '1-3 days', tips: ['Get at least 3 quotes', 'Buy in off-season (spring/fall) for 10-20% savings', 'Check for utility rebates on energy-efficient models', 'A higher SEER rating saves money long-term'], recommendation: 'Always hire a licensed HVAC contractor. Look for ENERGY STAR certified units for potential tax credits up to $2,000.' },
  'roof repair': { task: 'Roof Repair', diyCost: '50-300', proCost: '400-1,500', diyTime: '2-4 hours', proTime: '1-2 days', tips: ['Fix small issues before they become big ones', 'Buy materials at Home Depot/Lowes during seasonal sales', 'Check your insurance — storm damage is often covered', 'Consider roof coating to extend life by 5-10 years'], recommendation: 'Minor shingle replacement is DIY-friendly. Structural issues, flashing, or large areas need a pro.' },
  'plumbing repair': { task: 'Plumbing Repair', diyCost: '20-100', proCost: '150-500', diyTime: '1-2 hours', proTime: 'Same day', tips: ['Learn to fix a running toilet yourself (saves $150+)', 'A $30 drain snake prevents $200+ plumber calls', 'Fix drips promptly — a dripping faucet wastes 3,000+ gallons/year', 'YouTube tutorials cover most basic plumbing fixes'], recommendation: 'Clogs, running toilets, and faucet replacements are great DIY projects. Call a pro for anything involving main lines or water heater.' },
  'electrical work': { task: 'Electrical Work', diyCost: '20-100', proCost: '150-800', diyTime: '1-3 hours', proTime: '2-8 hours', tips: ['Outlet and switch replacements are simple DIY', 'Always turn off breaker before any electrical work', 'LED bulb conversion saves $100+/year on energy', 'Get multiple quotes for panel upgrades'], recommendation: 'Simple outlet/switch replacements are DIY-safe. ALWAYS hire a licensed electrician for panel work, new circuits, or anything you\'re unsure about.' },
  'painting': { task: 'Interior/Exterior Painting', diyCost: '200-800', proCost: '1,500-5,000', diyTime: '2-5 days', proTime: '2-5 days', tips: ['Buy paint during holiday sales (Memorial Day, Labor Day)', 'One coat of premium paint often beats two coats of cheap paint', 'Rent a sprayer for large areas ($50-75/day)', 'Proper prep (sanding, priming) is 80% of a good paint job'], recommendation: 'Painting is one of the best DIY projects — huge savings with decent results. Hire a pro for multi-story exteriors or if you want flawless results.' },
  'water heater': { task: 'Water Heater Replacement', diyCost: '300-600', proCost: '800-2,500', diyTime: '3-5 hours', proTime: 'Same day', tips: ['Tankless units cost more upfront but last 20+ years vs 10-12 for tank', 'Check for utility rebates on heat pump water heaters', 'Lowes and Home Depot often include basic installation', 'Insulate your current tank for $20 to improve efficiency'], recommendation: 'Experienced DIYers can replace a tank water heater. Gas water heaters and tankless installations should be done by a licensed plumber.' },
  default: { task: 'Home Maintenance Task', diyCost: '25-200', proCost: '150-1,000', diyTime: 'Varies', proTime: 'Varies', tips: ['Always get 3 quotes for professional work', 'Check Angi, Thumbtack, and NextDoor for contractor reviews', 'Many home repairs have great YouTube tutorials', 'Buy tools during Black Friday sales — they pay for themselves'], recommendation: 'Research the specific task to determine if it\'s DIY-appropriate. When in doubt, get a professional assessment first.' },
};

export default function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { task, zipCode } = req.body;
  const key = task?.toLowerCase() || '';
  const match = Object.keys(estimates).find(k => key.includes(k)) || 'default';

  res.status(200).json(estimates[match]);
}
